/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/articles/{slug}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{slug}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Comments.CommentsEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Comments.CommentsEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Comments.CommentsEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Conduit.Features.Comments.Create.Model"];
                    "text/json": components["schemas"]["Conduit.Features.Comments.Create.Model"];
                    "application/*+json": components["schemas"]["Conduit.Features.Comments.Create.Model"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{slug}/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    tag?: string;
                    author?: string;
                    favorited?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Articles.ArticlesEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Articles.ArticlesEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Articles.ArticlesEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Conduit.Features.Articles.Create.Command"];
                    "text/json": components["schemas"]["Conduit.Features.Articles.Create.Command"];
                    "application/*+json": components["schemas"]["Conduit.Features.Articles.Create.Command"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    tag?: string;
                    author?: string;
                    favorited?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Articles.ArticlesEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Articles.ArticlesEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Articles.ArticlesEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Conduit.Features.Articles.Edit.Model"];
                    "text/json": components["schemas"]["Conduit.Features.Articles.Edit.Model"];
                    "application/*+json": components["schemas"]["Conduit.Features.Articles.Edit.Model"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Articles.ArticleEnvelope"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Profiles.ProfileEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Profiles.ProfileEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Profiles.ProfileEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{username}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Profiles.ProfileEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Profiles.ProfileEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Profiles.ProfileEnvelope"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Profiles.ProfileEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Profiles.ProfileEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Profiles.ProfileEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Tags.TagsEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Tags.TagsEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Tags.TagsEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Users.UserEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Users.UserEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Users.UserEnvelope"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Conduit.Features.Users.Edit.Command"];
                    "text/json": components["schemas"]["Conduit.Features.Users.Edit.Command"];
                    "application/*+json": components["schemas"]["Conduit.Features.Users.Edit.Command"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Users.UserEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Users.UserEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Users.UserEnvelope"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Conduit.Features.Users.Create.Command"];
                    "text/json": components["schemas"]["Conduit.Features.Users.Create.Command"];
                    "application/*+json": components["schemas"]["Conduit.Features.Users.Create.Command"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Conduit.Features.Users.Login.Command"];
                    "text/json": components["schemas"]["Conduit.Features.Users.Login.Command"];
                    "application/*+json": components["schemas"]["Conduit.Features.Users.Login.Command"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Conduit.Features.Users.UserEnvelope"];
                        "application/json": components["schemas"]["Conduit.Features.Users.UserEnvelope"];
                        "text/json": components["schemas"]["Conduit.Features.Users.UserEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Conduit.Domain.Article": {
            slug?: string | null;
            title?: string | null;
            description?: string | null;
            body?: string | null;
            author?: components["schemas"]["Conduit.Domain.Person"];
            comments?: components["schemas"]["Conduit.Domain.Comment"][];
            readonly favorited?: boolean;
            /** Format: int32 */
            readonly favoritesCount?: number;
            readonly tagList?: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "Conduit.Domain.Comment": {
            /** Format: int32 */
            id?: number;
            body?: string | null;
            author?: components["schemas"]["Conduit.Domain.Person"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "Conduit.Domain.Person": {
            username?: string | null;
            bio?: string | null;
            image?: string | null;
            following?: boolean;
        };
        "Conduit.Features.Articles.ArticleEnvelope": {
            article?: components["schemas"]["Conduit.Domain.Article"];
        };
        "Conduit.Features.Articles.ArticlesEnvelope": {
            articles?: components["schemas"]["Conduit.Domain.Article"][];
            /** Format: int32 */
            articlesCount?: number;
        };
        "Conduit.Features.Articles.Create.ArticleData": {
            title?: string | null;
            description?: string | null;
            body?: string | null;
            tagList?: string[] | null;
        };
        "Conduit.Features.Articles.Create.Command": {
            article?: components["schemas"]["Conduit.Features.Articles.Create.ArticleData"];
        };
        "Conduit.Features.Articles.Edit.ArticleData": {
            title?: string | null;
            description?: string | null;
            body?: string | null;
            tagList?: string[] | null;
        };
        "Conduit.Features.Articles.Edit.Model": {
            article?: components["schemas"]["Conduit.Features.Articles.Edit.ArticleData"];
        };
        "Conduit.Features.Comments.CommentsEnvelope": {
            comments?: components["schemas"]["Conduit.Domain.Comment"][];
        };
        "Conduit.Features.Comments.Create.CommentData": {
            body?: string | null;
        };
        "Conduit.Features.Comments.Create.Model": {
            comment?: components["schemas"]["Conduit.Features.Comments.Create.CommentData"];
        };
        "Conduit.Features.Profiles.Profile": {
            username?: string | null;
            bio?: string | null;
            image?: string | null;
            following?: boolean;
        };
        "Conduit.Features.Profiles.ProfileEnvelope": {
            profile?: components["schemas"]["Conduit.Features.Profiles.Profile"];
        };
        "Conduit.Features.Tags.TagsEnvelope": {
            tags?: string[];
        };
        "Conduit.Features.Users.Create.Command": {
            user?: components["schemas"]["Conduit.Features.Users.Create.UserData"];
        };
        "Conduit.Features.Users.Create.UserData": {
            username?: string | null;
            email?: string | null;
            password?: string | null;
        };
        "Conduit.Features.Users.Edit.Command": {
            user?: components["schemas"]["Conduit.Features.Users.Edit.UserData"];
        };
        "Conduit.Features.Users.Edit.UserData": {
            username?: string | null;
            email?: string | null;
            password?: string | null;
            bio?: string | null;
            image?: string | null;
        };
        "Conduit.Features.Users.Login.Command": {
            user?: components["schemas"]["Conduit.Features.Users.Login.UserData"];
        };
        "Conduit.Features.Users.Login.UserData": {
            email?: string | null;
            password?: string | null;
        };
        "Conduit.Features.Users.User": {
            username?: string | null;
            email?: string | null;
            bio?: string | null;
            image?: string | null;
            token?: string | null;
        };
        "Conduit.Features.Users.UserEnvelope": {
            user?: components["schemas"]["Conduit.Features.Users.User"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
